### ISSUE TITLE
Scripts fails on Fedora 36

### ISSUE THREAD

**Issue by sprl68** [sukhmeetbawa/OpenCL-AMD-Fedora#3]
I'm getting the following error: Error: Unable to find a match: rocm-opencl-runtime

**Comment by sukhmeetbawa** [comment]
I have fixed the issue you can try now.

**Comment by sprl68** [comment]
I'm still getting the same error, tried uninstall and then intall again but no luck, full message reads:

Legacy Drivers are are required for Arctic Islands/Polaris
Latest Drivers work with Vega and Above
1) Install-OpenCL-Latest  3) Install-HIP-Latest	    5) Quit
2) Install-OpenCL-Legacy  4) Uninstall
Enter Option Number: 1
Installing Latest OpenCL Stack
Installing Workaroud Package
Copr repo for amdgpu-core-shim owned by sukhmee 8.7 kB/s | 3.3 kB     00:00    
Dependencies resolved.
================================================================================
 Package
     Arch   Version
                 Repository                                                Size
================================================================================
Installing:
 amdgpu-core-shim
     x86_64 0-1.fc36
                 copr:copr.fedorainfracloud.org:sukhmeet:amdgpu-core-shim 6.6 k

Transaction Summary
================================================================================
Install  1 Package

Total download size: 6.6 k
Installed size: 0  
Downloading Packages:
amdgpu-core-shim-0-1.fc36.x86_64.rpm             35 kB/s | 6.6 kB     00:00    
--------------------------------------------------------------------------------
Total                                            35 kB/s | 6.6 kB     00:00     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1 
  Installing       : amdgpu-core-shim-0-1.fc36.x86_64                       1/1 
  Verifying        : amdgpu-core-shim-0-1.fc36.x86_64                       1/1 

Installed:
  amdgpu-core-shim-0-1.fc36.x86_64                                              

Complete!
Installing OpenCL Runtime
Last metadata expiration check: 0:00:02 ago on Tue 14 Jun 2022 01:33:45 PM CDT.
No match for argument: rocm-opencl-runtime
Error: Unable to find a match: rocm-opencl-runtime
